version: "3.8"

services:
  frontend:
    build:
      context: ./frontend         # Folder should be ./frontend
      dockerfile: Dockerfile      # Dockerfile inside ./frontend
    ports:
      - "5002:5000"               # Use 5002 to avoid conflict with API (if API uses 5000 internally too)
    depends_on:
      - api
    volumes:
      - ./frontend:/app           # Mount frontend folder

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./api:/api

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:

