version: "3.8"

services:
  web:
    build:
      context: ./web           # Use the web folder for the web service
      dockerfile: Dockerfile   # Dockerfile inside web folder (if you have one)
    ports:
      - "5000:5000"
    depends_on:
      - api
    volumes:
      - ./web:/app             # Mount web folder to /app inside container

  api:
    build:
      context: ./api          # Build API from api folder
      dockerfile: Dockerfile  # Dockerfile inside api folder
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/api            # Mount api folder to /api inside container

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:

