version: "3.8"
services:
  frontend:
    build: ./frontend
    # Remove this whole healthcheck section:
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3

