name: CI Pipeline

on:
  push:
    branches:
      - main   # or your default branch name
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.20.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker containers
        run: docker-compose build

      - name: Start containers in detached mode
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

