name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
      - feature/devops-setup
    paths:
      - '**.py'
      - 'api/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/devops.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d --build
          sleep 10

      - name: Test Random Quote API
        run: curl http://localhost:5000/random

