name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build Containers
        run: docker-compose build
      
      - name: Run App
        run: docker-compose up -d
