name: CI Pipeline

on:
  push:
    branches:
      - main      # or your default branch
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for modern Docker builds)
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (optional, if you push images)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}    # set these in repo secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker containers
        run: docker-compose build

      - name: Start containers in detached mode
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

